interface TradeCardProps {
  pair: string;
  tradeType: string;
  lastUpdate: string;
  profitPercent: number;
  profitDirection?: "up" | "down";
  target: number;
  entryDate: string;
}

export const cards = [
  {
    pair: "NEAR/USDT",
    tradeType: "SPOT",
    lastUpdate: "1 хв. назад",
    profitPercent: 58.62,
    profitDirection: "up",
    target: 4,
    entryDate: "06.10.2022",
  },
  {
    pair: "BTC/USDT",
    tradeType: "FUTURES",
    lastUpdate: "2 хв. назад",
    profitPercent: 12.35,
    profitDirection: "up",
    target: 1,
    entryDate: "07.10.2022",
  },
  {
    pair: "ETH/USDT",
    tradeType: "SPOT",
    lastUpdate: "5 хв. назад",
    profitPercent: -3.42,
    profitDirection: "down",
    target: 2,
    entryDate: "08.10.2022",
  },
  {
    pair: "BNB/USDT",
    tradeType: "SPOT",
    lastUpdate: "10 хв. назад",
    profitPercent: 25.8,
    profitDirection: "up",
    target: 3,
    entryDate: "09.10.2022",
  },
  {
    pair: "SOL/USDT",
    tradeType: "FUTURES",
    lastUpdate: "1 годину тому",
    profitPercent: 7.12,
    profitDirection: "up",
    target: 4,
    entryDate: "10.10.2022",
  },
  {
    pair: "ADA/USDT",
    tradeType: "SPOT",
    lastUpdate: "2 години тому",
    profitPercent: 0.0,
    profitDirection: "up",
    target: 2,
    entryDate: "11.10.2022",
  },
  {
    pair: "DOT/USDT",
    tradeType: "SPOT",
    lastUpdate: "5 годин тому",
    profitPercent: 13.5,
    profitDirection: "up",
    target: 1,
    entryDate: "12.10.2022",
  },
  {
    pair: "XRP/USDT",
    tradeType: "FUTURES",
    lastUpdate: "1 хв. назад",
    profitPercent: -2.14,
    profitDirection: "down",
    target: 3,
    entryDate: "13.10.2022",
  },
  {
    pair: "MATIC/USDT",
    tradeType: "SPOT",
    lastUpdate: "15 хв. назад",
    profitPercent: 9.99,
    profitDirection: "up",
    target: 4,
    entryDate: "14.10.2022",
  },
  {
    pair: "DOGE/USDT",
    tradeType: "FUTURES",
    lastUpdate: "30 хв. назад",
    profitPercent: 1.25,
    profitDirection: "up",
    target: 1,
    entryDate: "15.10.2022",
  },
  {
    pair: "LTC/USDT",
    tradeType: "SPOT",
    lastUpdate: "2 хв. назад",
    profitPercent: -5.6,
    profitDirection: "down",
    target: 3,
    entryDate: "16.10.2022",
  },
  {
    pair: "TRX/USDT",
    tradeType: "FUTURES",
    lastUpdate: "3 хв. назад",
    profitPercent: 4.75,
    profitDirection: "up",
    target: 2,
    entryDate: "17.10.2022",
  },
  {
    pair: "AVAX/USDT",
    tradeType: "SPOT",
    lastUpdate: "8 хв. назад",
    profitPercent: 11.11,
    profitDirection: "up",
    target: 4,
    entryDate: "18.10.2022",
  },
  {
    pair: "UNI/USDT",
    tradeType: "FUTURES",
    lastUpdate: "45 хв. назад",
    profitPercent: 6.0,
    profitDirection: "up",
    target: 1,
    entryDate: "19.10.2022",
  },
  {
    pair: "AAVE/USDT",
    tradeType: "SPOT",
    lastUpdate: "1 день тому",
    profitPercent: -10.2,
    profitDirection: "down",
    target: 5,
    entryDate: "20.10.2022",
  },
  {
    pair: "SUSHI/USDT",
    tradeType: "FUTURES",
    lastUpdate: "2 дні тому",
    profitPercent: 15.65,
    profitDirection: "up",
    target: 2,
    entryDate: "21.10.2022",
  },
  {
    pair: "FIL/USDT",
    tradeType: "SPOT",
    lastUpdate: "5 хв. назад",
    profitPercent: 2.9,
    profitDirection: "up",
    target: 3,
    entryDate: "22.10.2022",
  },
  {
    pair: "LINK/USDT",
    tradeType: "FUTURES",
    lastUpdate: "1 хв. назад",
    profitPercent: -1.88,
    profitDirection: "down",
    target: 4,
    entryDate: "23.10.2022",
  },
  {
    pair: "FTM/USDT",
    tradeType: "SPOT",
    lastUpdate: "30 хв. назад",
    profitPercent: 33.3,
    profitDirection: "up",
    target: 3,
    entryDate: "24.10.2022",
  },
  {
    pair: "NEAR/BTC",
    tradeType: "SPOT",
    lastUpdate: "1 хв. назад",
    profitPercent: 3.33,
    profitDirection: "up",
    target: 1,
    entryDate: "25.10.2022",
  },
] as TradeCardProps[];
